=== denis-vilyuzhanin/OpenModelSphereMirror/workspace/org.modelsphere.guide/help_sms/pages/tree.dtd
<!ELEMENT tree (branch+)>
   <!ELEMENT branch (branchText,(branch|leaf)*)>
   <!ATTLIST branch id CDATA #REQUIRED>
   <!ELEMENT branchText (#PCDATA)>
   <!ELEMENT leaf (leafText,link)>
   <!ELEMENT leafText (#PCDATA)>
   <!ELEMENT link (#PCDATA)>

=== denis-vilyuzhanin/OpenModelSphereMirror/workspace/org.modelsphere.guide/help_sms/pages/tree_fr.xml
<?xml version="1.0" encoding="ISO-8859-1"?><?xml-stylesheet type="text/xsl" href="xmlTree.xsl"?><!DOCTYPE tree SYSTEM 'tree.dtd'>
<tree>
  <branch id="Bienvenue">
    <branchText>Bienvenue</branchText>
    <leaf>
      <leafText>Introduction</leafText>
      <link>html/fr_0010_intro.html</link>
    </leaf>
    <leaf>
      <leafText>Qu'est-ce que Open ModelSphere?</leafText>
      <link>html/fr_0020_whatis.html</link>
    </leaf>
  </branch>
  <branch id="CommentinstallerModelSphere">
    <branchText>Comment installer ModelSphere</branchText>
    <leaf>
      <leafText>Installation et exigences minimales</leafText>
      <link>html/fr_0110_requirement.html</link>
    </leaf>
    <leaf>
      <leafText>Assistant de création de modèles</leafText>
      <link>html/fr_0125_model_creation_wizard.html</link>
    </leaf>
    <leaf>
      <leafText>Redémarrage en mode sûr</leafText>
      <link>html/fr_0130_safemode.html</link>
    </leaf>
  </branch>
  <branch id="Lenvironnementdetravail">
    <branchText>L'environnement de travail</branchText>
    <leaf>
      <leafText>La sélection</leafText>
      <link>html/fr_0210_selectmanager.html</link>
    </leaf>
    <leaf>
      <leafText>Les menus</leafText>
      <link>html/fr_0220_menu.html</link>
    </leaf>
    <leaf>
      <leafText>Les barres d'outils</leafText>
      <link>html/fr_0230_toolbars.html</link>
    </leaf>
    <leaf>
      <leafText>L'explorateur</leafText>
      <link>html/fr_0240_explorer.html</link>
    </leaf>
    <leaf>
      <leafText>La fenêtre du diagramme</leafText>
      <link>html/fr_0245_diagram_win.html</link>
    </leaf>
    <leaf>
      <leafText>La barre d'état</leafText>
      <link>html/fr_0250_statusbar.html</link>
    </leaf>
    <leaf>
      <leafText>Le panneau de conception</leafText>
      <link>html/fr_0260_designpanel.html</link>
    </leaf>
    <leaf>
      <leafText>La fenêtre de proriétés</leafText>
      <link>html/fr_0270_propertieswin.html</link>
    </leaf>
    <leaf>
      <leafText>La fenêtre de listes</leafText>
      <link>html/fr_0280_lists.html</link>
    </leaf>
    <leaf>
      <leafText>Modification des options</leafText>
      <link>html/fr_0290_options.html</link>
    </leaf>
  </branch>
  <branch id="Informationdeconceptionetdemodélisation">
    <branchText>Information de conception et de modélisation</branchText>
    <leaf>
      <leafText>Objets sémantiques et espace de nommage</leafText>
      <link>html/fr_0305_namespace.html</link>
    </leaf>
    <leaf>
      <leafText>Le concept de projet</leafText>
      <link>html/fr_0310_project.html</link>
    </leaf>
  </branch>
  <branch id="Lescomposantesprédéfinies">
    <branchText>Les composantes prédéfinies</branchText>
    <leaf>
      <leafText>Le noeud prédéfini</leafText>
      <link>html/fr_0315_buitin_node.html</link>
    </leaf>
    <leaf>
      <leafText>Le système cible</leafText>
      <link>html/fr_0320_targetsystem.html</link>
    </leaf>
    <leaf>
      <leafText>Le noeud d'utilisateurs</leafText>
      <link>html/fr_0325_usernode.html</link>
    </leaf>
    <branch id="ExtensionUML">
      <branchText>Extension UML</branchText>
      <leaf>
        <leafText>Extension UML</leafText>
        <link>html/fr_0330_umlext.html</link>
      </leaf>
      <leaf>
        <leafText>Les stéréotypes</leafText>
        <link>html/fr_0331_uml_stereo.html</link>
      </leaf>
      <leaf>
        <leafText>Les contraintes</leafText>
        <link>html/fr_0332_uml_constr.html</link>
      </leaf>
    </branch>
    <leaf>
      <leafText>Les formalismes</leafText>
      <link>html/fr_0335_notations.html</link>
    </leaf>
  </branch>
  <branch id="Lescomposantesutilisateur">
    <branchText>Les composantes utilisateur</branchText>
    <leaf>
      <leafText>Les composantes utilisateur</leafText>
      <link>html/fr_0340_user_def_comp.html</link>
    </leaf>
    <leaf>
      <leafText>Le modèle de données</leafText>
      <link>html/fr_0345_datamodel.html</link>
    </leaf>
    <leaf>
      <leafText>Le modèle de domaines</leafText>
      <link>html/fr_0350_domainmodel.html</link>
    </leaf>
    <leaf>
      <leafText>Le modèle d'items communs</leafText>
      <link>html/fr_0355_comitmodel.html</link>
    </leaf>
    <leaf>
      <leafText>La bibliothèque d'opérations</leafText>
      <link>html/fr_0360_oplib.html</link>
    </leaf>
    <leaf>
      <leafText>La base de données</leafText>
      <link>html/fr_0365_database.html</link>
    </leaf>
    <leaf>
      <leafText>Le système cible utilisateur</leafText>
      <link>html/fr_0367_usertargetsys.html</link>
    </leaf>
    <leaf>
      <leafText>Le modèle de classes</leafText>
      <link>html/fr_0370_clasmodel.html</link>
    </leaf>
    <leaf>
      <leafText>Le modèle de processus</leafText>
      <link>html/fr_0375_processmodel.html</link>
    </leaf>
    <leaf>
      <leafText>Le modèle de liens</leafText>
      <link>html/fr_0380_linkmodel.html</link>
    </leaf>
    <leaf>
      <leafText>Le paquetage utilisateur</leafText>
      <link>html/fr_0383_userpack.html</link>
    </leaf>
  </branch>
  <branch id="Travailleraveclesdiagrammes">
    <branchText>Travailler avec les diagrammes</branchText>
    <leaf>
      <leafText>Les diagrammes</leafText>
      <link>html/fr_0385_diagram.html</link>
    </leaf>
    <leaf>
      <leafText>Information sémantique et graphique</leafText>
      <link>html/fr_0388_semgraphinfo.html</link>
    </leaf>
    <leaf>
      <leafText>Les duplicatas</leafText>
      <link>html/fr_0390_duplic.html</link>
    </leaf>
    <leaf>
      <leafText>Supprimer des objets</leafText>
      <link>html/fr_0393_delete.html</link>
    </leaf>
    <leaf>
      <leafText>Trouver l'information</leafText>
      <link>html/fr_0396_find_info.html</link>
    </leaf>
    <leaf>
      <leafText>Utilisation des styles</leafText>
      <link>html/fr_0405_styles.html</link>
    </leaf>
    <branch id="Lespropriétésdudiagramme">
      <branchText>Les propriétés du diagramme</branchText>
      <leaf>
        <leafText>Établir la surface de travail</leafText>
        <link>html/fr_0410_diagram.html</link>
      </leaf>
      <leaf>
        <leafText>Afficher la numérotation et le titre des pages</leafText>
        <link>html/fr_0411_page_number.html</link>
      </leaf>
      <leaf>
        <leafText>Montrer ou cacher le saut de page</leafText>
        <link>html/fr_0412_saut.html</link>
      </leaf>
      <leaf>
        <leafText>Définition de la numérotation et du titre des pages</leafText>
        <link>html/fr_0413_diagr_header.html</link>
      </leaf>
    </branch>
    <leaf>
      <leafText>Disposer les objets graphiques</leafText>
      <link>html/fr_0414_layout.html</link>
    </leaf>
    <leaf>
      <leafText>Le zoom, la vue d'ensemble et la loupe</leafText>
      <link>html/fr_0415_view_zoom.html</link>
    </leaf>
    <leaf>
      <leafText>Ajuster automatiquement</leafText>
      <link>html/fr_0420_autofit.html</link>
    </leaf>
    <leaf>
      <leafText>Dupliquer dans le diagramme</leafText>
      <link>html/fr_0390_duplic.html</link>
    </leaf>
    <leaf>
      <leafText>Repositionner</leafText>
      <link>html/fr_0430_reposit.html</link>
    </leaf>
    <leaf>
      <leafText>Changer les relations d'angle droit à angle libre</leafText>
      <link>html/fr_0435_r_angle.html</link>
    </leaf>
    <leaf>
      <leafText>Couleur et styles de lignes</leafText>
      <link>html/fr_0440_color.html</link>
    </leaf>
    <leaf>
      <leafText>Outils de dessins</leafText>
      <link>html/fr_0445_drawing.html</link>
    </leaf>
    <leaf>
      <leafText>Le cartouche</leafText>
      <link>html/fr_0450_stamp.html</link>
    </leaf>
    <leaf>
      <leafText>Insérer une image</leafText>
      <link>html/fr_0455_insertimage.html</link>
    </leaf>
    <leaf>
      <leafText>Créer des liens sémantiques et graphiques</leafText>
      <link>html/fr_0460_semanticlinks.html</link>
    </leaf>
    <leaf>
      <leafText>Utiliser les notes graphiques</leafText>
      <link>html/fr_0465_notes.html</link>
    </leaf>
    <leaf>
      <leafText>Utiliser la grille</leafText>
      <link>html/fr_0470_grid.html</link>
    </leaf>
    <leaf>
      <leafText>Glisser-déposer</leafText>
      <link>html/fr_0475_drag_drop.html</link>
    </leaf>
  </branch>
  <branch id="Modélisationconceptuellededonnées">
    <branchText>Modélisation conceptuelle de données</branchText>
    <leaf>
      <leafText>Les concepts de base</leafText>
      <link>html/fr_2505_basic_cdm.html</link>
    </leaf>
    <leaf>
      <leafText>Ajouter des entitées et des attributs</leafText>
      <link>html/fr_2510_entities_cdm.html</link>
    </leaf>
    <leaf>
      <leafText>Ajouter des clés primaires</leafText>
      <link>html/fr_2515_pk_cdm.html</link>
    </leaf>
    <leaf>
      <leafText>Ajouter des clés uniques</leafText>
      <link>html/fr_2520_uk_cdm.html</link>
    </leaf>
    <leaf>
      <leafText>Créer les associations</leafText>
      <link>html/fr_2525_relationships_cdm.html</link>
    </leaf>
    <leaf>
      <leafText>Modifier la multiplicité</leafText>
      <link>html/fr_2530_multi_cdm.html</link>
    </leaf>
    <leaf>
      <leafText>Manipulations d'associations</leafText>
      <link>html/fr_2533_relationship_manip_cdm.html</link>
    </leaf>
    <leaf>
      <leafText>Convertir un modèle conceptuel de données en modèle relationnel de données</leafText>
      <link>html/fr_2590_conversion_cdm.html</link>
    </leaf>
  </branch>
  <branch id="Modélisationrelationnellededonnées">
    <branchText>Modélisation relationnelle de données</branchText>
    <leaf>
      <leafText>Les concepts de base</leafText>
